logging.level.org.hibernate.SQL: DEBUG

spring.jpa.hibernate.ddl-auto: create-drop


spring.datasource.url: jdbc:mysql://localhost:3306/quiz?zeroDateTimeBehavior=convertToNull
spring.datasource.username: root

